config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks/new', to: 'tasks#new'

  get 'tasks', to: 'tasks#index', as: :tasks
  get 'tasks/:id', to: 'tasks#show', as: :task
  post 'tasks', to: 'tasks#create'

  get    "tasks/:id/edit", to: "tasks#edit", as: :update
  patch  "tasks/:id",      to: "tasks#update"

  delete "tasks/:id", to: "tasks#destroy", as: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
      puts " je passe dans Index"
      @tasks = Task.all
      p @tasks
  end

  def show

  end

  def new
    @task = Task.new
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def create
    @task = Task.create!(task_params)
    redirect_to tasks_path
  end

  def edit

  end

  def update

    @task.update(task_params)

    # no need for app/views/tasks/update.html.erb
    redirect_to task_path(@task)
  end

  def destroy

    @task.destroy
    redirect_to tasks_path
  end

 private

  def set_task
    @task = Task.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_task_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.label :completed %>
  <%= f.text_field :completed %>

  <%= f.submit %>
<% end %>

app/views/tasks/destroy.html.erb
destroy.html.erb

app/views/tasks/edit.html.erb
<h1>Update</h1>

<%= render 'task_form', task: @task %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<ul>
  <% @tasks.each do |task| %>
    <li><%= link_to task.title, task_path(task.id) %></li>
  <% end %>
</ul>

<p><%= link_to "Create a form", tasks_new_path %></p>

app/views/tasks/new.html.erb
<h1>New</h1>

<%= render 'task_form', task: @task %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>
<p><%= @task.completed %></p>


<%= link_to "Go back to tasks", tasks_path %>
<%= link_to "Update task", update_path %>
<%= link_to "Delete task", destroy_path,
method: "delete", data: { confirm: "Are you sure?" }%>

app/views/tasks/update.html.erb
update.html.erb